// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	WalletID      int32            `json:"wallet_id"`
	UserID        int32            `json:"user_id"`
	NetBalance    pgtype.Numeric   `json:"net_balance"`
	LastUpdatedAt pgtype.Timestamp `json:"last_updated_at"`
}

type PlaidAccount struct {
	ID           int32            `json:"id"`
	PlaidItemID  int32            `json:"plaid_item_id"`
	AccountID    string           `json:"account_id"`
	Name         string           `json:"name"`
	OfficialName pgtype.Text      `json:"official_name"`
	Type         string           `json:"type"`
	Subtype      pgtype.Text      `json:"subtype"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type PlaidItem struct {
	ID                 int32            `json:"id"`
	UserID             int32            `json:"user_id"`
	AccessToken        string           `json:"access_token"`
	ItemID             string           `json:"item_id"`
	InstitutionName    pgtype.Text      `json:"institution_name"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	TransactionsCursor pgtype.Text      `json:"transactions_cursor"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type Transaction struct {
	ID                      int32            `json:"id"`
	UserID                  int32            `json:"user_id"`
	PlaidAccountID          int32            `json:"plaid_account_id"`
	TransactionID           string           `json:"transaction_id"`
	AccountID               string           `json:"account_id"`
	Amount                  pgtype.Numeric   `json:"amount"`
	Date                    pgtype.Date      `json:"date"`
	AuthorizedDate          pgtype.Date      `json:"authorized_date"`
	Name                    string           `json:"name"`
	MerchantName            pgtype.Text      `json:"merchant_name"`
	Pending                 bool             `json:"pending"`
	PaymentChannel          string           `json:"payment_channel"`
	TransactionCode         pgtype.Text      `json:"transaction_code"`
	IsoCurrencyCode         pgtype.Text      `json:"iso_currency_code"`
	UnofficialCurrencyCode  pgtype.Text      `json:"unofficial_currency_code"`
	Location                []byte           `json:"location"`
	PaymentMeta             []byte           `json:"payment_meta"`
	PersonalFinanceCategory []byte           `json:"personal_finance_category"`
	Counterparties          []byte           `json:"counterparties"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	UpdatedAt               pgtype.Timestamp `json:"updated_at"`
}

type TransactionCategorization struct {
	ID                  int32            `json:"id"`
	TransactionID       int32            `json:"transaction_id"`
	WalletID            int32            `json:"wallet_id"`
	CategoryType        string           `json:"category_type"`
	CategorizedByUserID int32            `json:"categorized_by_user_id"`
	CategorizedAt       pgtype.Timestamp `json:"categorized_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Name         string           `json:"name"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Wallet struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type WalletMember struct {
	WalletID int32            `json:"wallet_id"`
	UserID   int32            `json:"user_id"`
	JoinedAt pgtype.Timestamp `json:"joined_at"`
}
