// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddWalletMember(ctx context.Context, arg AddWalletMemberParams) error
	CountTransactionsByUserID(ctx context.Context, userID int32) (int64, error)
	CreatePlaidAccount(ctx context.Context, arg CreatePlaidAccountParams) (PlaidAccount, error)
	CreatePlaidItem(ctx context.Context, arg CreatePlaidItemParams) (CreatePlaidItemRow, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionCategorization(ctx context.Context, arg CreateTransactionCategorizationParams) (TransactionCategorization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, name string) (Wallet, error)
	DeletePlaidItem(ctx context.Context, id int32) error
	DeleteTransactionCategorization(ctx context.Context, arg DeleteTransactionCategorizationParams) error
	GetBalanceByWalletAndUser(ctx context.Context, arg GetBalanceByWalletAndUserParams) (Balance, error)
	GetBalancesByWalletID(ctx context.Context, walletID int32) ([]GetBalancesByWalletIDRow, error)
	GetCategorizationByTransactionAndWallet(ctx context.Context, arg GetCategorizationByTransactionAndWalletParams) (TransactionCategorization, error)
	GetNextUncategorizedTransactionByUserID(ctx context.Context, arg GetNextUncategorizedTransactionByUserIDParams) (Transaction, error)
	GetPlaidAccountByAccountID(ctx context.Context, accountID string) (PlaidAccount, error)
	GetPlaidAccountsByItemID(ctx context.Context, plaidItemID int32) ([]PlaidAccount, error)
	GetPlaidItemByItemID(ctx context.Context, itemID string) (GetPlaidItemByItemIDRow, error)
	GetPlaidItemsByUserID(ctx context.Context, userID int32) ([]GetPlaidItemsByUserIDRow, error)
	GetSharedTransactionsByWalletID(ctx context.Context, walletID int32) ([]GetSharedTransactionsByWalletIDRow, error)
	GetTransactionByID(ctx context.Context, id int32) (Transaction, error)
	GetTransactionByPlaidTransactionID(ctx context.Context, transactionID string) (Transaction, error)
	GetTransactionsByUserID(ctx context.Context, userID int32) ([]Transaction, error)
	GetTransactionsByUserIDPaginated(ctx context.Context, arg GetTransactionsByUserIDPaginatedParams) ([]Transaction, error)
	GetUncategorizedTransactionsByUserID(ctx context.Context, arg GetUncategorizedTransactionsByUserIDParams) ([]Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetWalletByID(ctx context.Context, id int32) (Wallet, error)
	GetWalletByUserID(ctx context.Context, userID int32) (Wallet, error)
	GetWalletMembersByWalletID(ctx context.Context, walletID int32) ([]GetWalletMembersByWalletIDRow, error)
	RemoveWalletMember(ctx context.Context, arg RemoveWalletMemberParams) error
	UpdatePlaidItemAccessToken(ctx context.Context, arg UpdatePlaidItemAccessTokenParams) (UpdatePlaidItemAccessTokenRow, error)
	UpdatePlaidItemCursor(ctx context.Context, arg UpdatePlaidItemCursorParams) (UpdatePlaidItemCursorRow, error)
	UpdateTransactionPendingStatus(ctx context.Context, arg UpdateTransactionPendingStatusParams) error
	UpsertBalance(ctx context.Context, arg UpsertBalanceParams) (Balance, error)
}

var _ Querier = (*Queries)(nil)
